### ISSUE TITLE
Update to JDK7+ 

### ISSUE THREAD

**Issue by AlexBischof** [Tinkerforge/generators#39]
Is there any reason not to switch at least to JDK7? JDK6 is EOL and with JDK7 IPConnectionBase could be extended to 

`
public abstract class IPConnectionBase implements Closable {
  @Override
  public void close() {
    disconnect();
  }
}
`

That way i can use the IPConnection as follows

`
try(IPConnection ipconntion = new IPConnection()){
//snip
}
`

**Comment by borg42** [comment]
It is now implemented in the latest version in git and will be in the next release. We did not have to switch to 1.7, since Closeable is already available in 1.5.

You can use try(IPConnection ipcon = ...) in 1.7 (where Closeable extends AutoCloseable) but it is still backward compatible to 1.5.
