### ISSUE TITLE
RFE: Function to get Device from Device ID

### ISSUE THREAD

**Issue by neilcsmith-net** [Tinkerforge/generators#41]
It would be great if there was a function built into the Java bindings that maps device ID to the Device sub-class that supports it.  I would imagine this could also be useful in other languages.

Something like -

``` java
public Class<? extends Device> getDeviceClass(int deviceID)
```

At the moment I need to keep a manually built list up-to-date to auto-create devices on enumeration, as in this code -

https://github.com/praxis-live/praxis/blob/master/praxis.tinkerforge/src/net/neilcsmith/praxis/tinkerforge/TFDeviceFactory.java

**Comment by photron** [comment]
Do you really need a getDeviceClass method? Wouldn't a createDevice method be better, because that's what you want to do in the end, isn't it?

```java
class DeviceFactory {
    static Device createDevice(int deviceIdentifier, String uid, IPConnection ipcon);
}
```

**Comment by neilcsmith-net** [comment]
On 11 Aug 2015 18:02, "Matthias Bolte" <notifications@github.com> wrote:
>
> Do you really need a getDeviceClass method? Wouldn't a createDevice
method be better, because that's what you want to do in the end, isn't it?

At the moment that's all I'm doing, so yes that would suit me right now.
However, I can think of various reasons that people might want to map a
device identifier to a class, so that they could analyse it using
reflection. You don't need an instance to do that, so it might be better
not to force it to be created. The id to class mapping currently requires
manual work - everything else should be achievable using standard Java APIs.

Thanks, Neil

Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

**Comment by photron** [comment]
Okay, so what about this?

```java
package com.tinkerforge;

public class DeviceFactory {
	public static Device createDevice(int deviceIdentifier, String uid, IPConnection ipcon) throws Exception {
		return getDeviceClass(deviceIdentifier).getConstructor(String.class, IPConnection.class).newInstance(uid, ipcon);
	}

	public static Class<? extends Device> getDeviceClass(int deviceIdentifier) {
		switch (deviceIdentifier) {
		case BrickDC.DEVICE_IDENTIFIER: return BrickDC.class;
		// ...
		case BrickletVoltageCurrent.DEVICE_IDENTIFIER: return BrickletVoltageCurrent.class;
		default: throw new IllegalArgumentException("Unknown device identifier: " + deviceIdentifier);
		}
	}
}
```

**Comment by NobodysNightmare** [comment]
:+1:

Am 12. August 2015 16:04:53 MESZ, schrieb Matthias Bolte <notifications@github.com>:
>Okay, so what about this?
>
>```java
>package com.tinkerforge;
>
>public class DeviceFactory {
>	public static Device createDevice(int deviceIdentifier, String uid,
>IPConnection ipcon) throws Exception {
>		return getDeviceClass(deviceIdentifier).getConstructor(String.class,
>IPConnection.class).newInstance(uid, ipcon);
>	}
>
>	public static Class<? extends Device> getDeviceClass(int
>deviceIdentifier) {
>		switch (deviceIdentifier) {
>		case BrickDC.DEVICE_IDENTIFIER: return BrickDC.class;
>		// ...
>		case BrickletVoltageCurrent.DEVICE_IDENTIFIER: return
>BrickletVoltageCurrent.class;
>		default: throw new IllegalArgumentException("Unknown device
>identifier: " + deviceIdentifier);
>		}
>	}
>}
>```
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Tinkerforge/generators/issues/41#issuecomment-130315918

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by neilcsmith-net** [comment]
Yep, looks great! (and familiar :wink:  )

**Comment by photron** [comment]
Please try this version of the Java bindings:

http://download.tinkerforge.com/_stuff/tinkerforge_java_bindings_2_1_5_device_factory.zip

**Comment by neilcsmith-net** [comment]
Apologies, somehow missed the message above.  Will check and get back to you ASAP.

**Comment by neilcsmith-net** [comment]
OK, I'm lousy at following up :disappointed: Sorry, other things (of the paid variety) got in the way of testing this sooner.  Seems fine.  My code has changed slightly too, and I _am_ now making use of getDeviceClass() before construction of the Device.

Be great to get this added in an official release, though will be included as here in the next Praxis LIVE release.

Big thanks!
