### ISSUE TITLE
generate_csharp_bindings.py broken?

### ISSUE THREAD

**Issue by suchja** [Tinkerforge/generators#45]
Probably it is just my missing knowledge about Python, but when I execute `python generate_csharp_bindings.py` I get the following error:

```
Traceback (most recent call last):
  File "generate_csharp_bindings.py", line 33, in <module>
    import common
ImportError: No module named common
```

I'm using Python 2.7.10 as provided by official docker image (i.e. with buildpack-deps). I do understand that the script cannot find `common.py` in the base folder. I did `git clone git@github.com:Tinkerforge/generators.git generators` and do have the `common.py` file. Do I need to set any path?

**Comment by photron** [comment]
This should work just as you did it. It works here with Python 2.7.6.

Could you modify `generate_csharp_bindings.py` and add the three print statements (see below)? Then run the script again and post the output of the three prints.

```py
from xml.sax.saxutils import escape
print 'getcwd', os.getcwd() # add this line
print 'before', sys.path # and this line
sys.path.append(os.path.split(os.getcwd())[0])
print 'after', sys.path # and this line
import common
```

**Comment by suchja** [comment]
@photron Thanks a ton for your immediate feedback. It was clearly my fault. Although I cloned everything to my host machine, I only mounted the csharp-folder into the python-container. Thanks to your print statements it was obvious now even to me. When mounting the whole generators folder, everything runs smoothly. Thanks!
