### ISSUE TITLE
IPCON_CONNECTED_CALLBACK registration is broken (C/C++ code)

### ISSUE THREAD

**Issue by aleh-arol** [Tinkerforge/generators#48]
Subj is broken due to commit cf5fce5ef16fb6713abf3d74f3229069d5fbc239 changing registration routine (filtering out callbacks with ID == 0).
Not sure whatever was an intention - to change IPCON_CONNECTED_CALLBACK id to something other than 0 (not done), or the filtering by callback id during registration is buggy.

**Comment by aleh-arol** [comment]
2.1.15 affected and all examples in the docs on website as well

**Comment by photron** [comment]
This is fixed in 2.1.16 now. Thanks for reporting the problem.
