### ISSUE TITLE
Optional callbacks not getting called in JavaScript.

### ISSUE THREAD

**Issue by Caserage** [Tinkerforge/generators#50]
When calling functions with the optional callbacks, the callback never gets called even though the desired function is executed.

Example:
```javascript
const tf = require('tinkerforge');
const ip = new tf.IPConnection();

ip.on(tf.IPConnection.CALLBACK_CONNECTED, () => {
  const lcd = new tf.BrickletLCD20x4('qHW', ip);
  lcd.backlightOn(() => {
    // This never gets called
    console.log('Callback called');
  });
});

ip.connect('localhost', 4223);
```

This should be fixed. Some implementations might not work because they're always waiting for a callback that will never be executed.

**Comment by photron** [comment]
Thanks for reporting this problem.
